app:
 ms:
  nobel:
   url: https://api.nobelprize.org/2.1
server:
 servlet:
  context-path: /ricoh
jwt:
 secret: javainuse
spring:
 datasource:
  url: jdbc:h2:mem:mydb
  username: sa
  password: password
  driverClassName: org.h2.Driver
 jpa:
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
 h2:
  console:
   enabled: true
 main:
  allow-bean-definition-overriding: true
 profiles:
  active: development